<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Entities\" />
    <Folder Include="Exceptions\" />
    <Folder Include="Enums\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Learning_Service.ValueObjects\Learning_Service.ValueObjects.csproj" />
  </ItemGroup>

</Project>
