<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Learning_Service.Domain\Learning_Service.Domain.csproj" />
    <ProjectReference Include="..\Learning_Service.ValueObjects\Learning_Service.ValueObjects.csproj" />
  </ItemGroup>

</Project>
